version: '3'

services:
  hos-microsite-ms:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: local
    ports:
      - "8099:8088"
    links:
      - mongo
      - redis
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules
     - ./logs:/logs
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    volumes:
      - './data:/data/db'
    ports:
      - 27049:27017
  redis:
     image: redis
     ports:
       - 6369:6379
